"""Report assembly: REPORT.md + a self-contained index.html.

The renderers (markdown/html skeleton, CSS) and the metric-row
builders live in :mod:`caustica.report.html`; this module keeps only what is
scenario-specific — the Setup/planner rows and the focus_study framing.
Both renderers show the SAME numbers from metrics.json.
"""

from __future__ import annotations

import json
from pathlib import Path

from apps.focus_study.scenarios import Setup
from caustica.report.html import (
    FIG_CAPTIONS,
    focal_spot_rows,
    focus_rows,
    harmonics_rows,
    render_html,
    render_markdown,
    run_rows,
)
from caustica.report.html import (
    fmt as _f,
)


def _rows(setup: Setup, m: dict, est: dict | None, elapsed_s: float) -> list[tuple[str, str, str]]:
    """(section, label, value) triples — the single source for both renderers."""
    g = setup.geometry_summary
    rows: list[tuple[str, str, str]] = []

    def add(section: str, label: str, value: str) -> None:
        rows.append((section, label, value))

    add("Setup", "solver", f"{setup.knobs.solver} (numpy / CPU)")
    add(
        "Setup",
        "drive",
        f"{setup.knobs.f0 / 1e6:g} MHz CW, {setup.knobs.amplitude / 1e6:g} MPa at the source",
    )
    add(
        "Setup",
        "grid",
        f"{'x'.join(map(str, g['shape']))} @ dx={g['dx_mm']} mm ({g['n_voxels']:,} voxels)",
    )
    add(
        "Setup",
        "domain",
        f"{' x '.join(f'{e:g}' for e in g['extent_mm'])} mm, PML {g['pml_vox']} vox",
    )
    add("Setup", "points per wavelength", f"{g['ppw_at_f0']} at f0 / {g['ppw_at_2f0']} at 2f0")
    add(
        "Setup",
        "geometry",
        f"ROC {g['roc_mm']} mm, aperture radius "
        f"{_f(g['aperture_radius_mm'])} mm, F/{_f(g['f_number'])}",
    )
    add("Setup", "source voxels", f"{g['source_voxels']:,}")
    add(
        "Setup",
        "medium",
        f"c = {g['c_min_max'][0]:g}–{g['c_min_max'][1]:g} m/s, "
        f"{'linear' if g['linear_medium'] else 'nonlinear (beta > 0)'}",
    )

    rows += focus_rows(m)
    rows += focal_spot_rows(m)
    rows += run_rows(m, wall_time=f"{elapsed_s:.1f} s on this CPU")
    rows += harmonics_rows(m)

    if "vs_oneill" in m:
        o = m["vs_oneill"]
        win = o["focal_window_mm"]
        add(
            "Analytic check",
            "focal-window correlation r",
            f"{o['pearson_r_focal_region']} (z = {win[0]}–{win[1]} mm)",
        )
        add(
            "Analytic check",
            "full-axis correlation r",
            f"{o['pearson_r_axial_shape']} (includes the near field)",
        )
        add("Analytic check", "normalized L2 difference", f"{o['rel_l2_pct']} %")
        add(
            "Analytic check",
            "peak position sim vs O'Neil",
            f"{o['peak_z_sim_mm']} vs {o['peak_z_oneill_mm']} mm (delta {o['peak_z_diff_mm']} mm)",
        )

    if est:
        # Only claim a local prediction when one was actually measured here;
        # otherwise the number is the datasheet GPU model and saying "this
        # CPU" would be a fabrication.
        if est["source"] == "measured":
            add(
                "Planner",
                "measured on this machine",
                f"{est['t_step_ms']} ms/step -> {est['t_expected_s']:.0f} s expected, "
                f"{est['t_worst_s']:.0f} s worst case",
            )
        add("Planner", "memory footprint of this run", f"{est['vram_gib']:.2f} GiB")
        add(
            "Planner",
            f"same run on an {est['gpu']} (datasheet)",
            f"{est['gpu_t_expected_s']:.1f} s, fits: {_f(est['gpu_fits'])}",
        )
    return rows


def write_markdown(
    outdir: Path, setup: Setup, m: dict, est: dict | None, figs: list[str], elapsed_s: float
) -> Path:
    return render_markdown(
        outdir / "REPORT.md",
        title=setup.title,
        description=setup.description,
        lede=f"*Generated by `apps/focus_study` — scenario `{setup.name}`, "
        "caustica on the numpy (CPU) backend.*",
        rows=_rows(setup, m, est, elapsed_s),
        notes=setup.notes,
        figs=figs,
        captions=FIG_CAPTIONS,
        files_lines=[
            "- `metrics.json` — every number above, machine-readable",
            "- `fields.npz` — fundamental amplitude/phase, p_max, harmonic amplitudes, axes",
            "- `index.html` — the same report with the figures inline",
        ],
    )


def write_html(
    outdir: Path, setup: Setup, m: dict, est: dict | None, figs: list[str], elapsed_s: float
) -> Path:
    return render_html(
        outdir / "index.html",
        page_title=f"focus_study — {setup.name}",
        title=setup.title,
        description=setup.description,
        rows=_rows(setup, m, est, elapsed_s),
        notes=setup.notes,
        figs=figs,
        captions=FIG_CAPTIONS,
        foot_html=(
            "<p class='foot'>Generated by <code>apps/focus_study</code> "
            f"(scenario <code>{setup.name}</code>) on the numpy CPU backend. "
            "Raw arrays in <code>fields.npz</code>, all numbers in <code>metrics.json</code>.</p>"
        ),
    )


def write_metrics(outdir: Path, payload: dict) -> Path:
    path = outdir / "metrics.json"
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path
